version: '3.8'

services:
  db:
    image: 'postgres'
    ports:
      - 5432:5432
    env_file:
      - docker/postgres/postgres.env
    volumes:
      - ./SQL/:/SQL/

  db_admin:
    build:
      dockerfile: docker/pgadmin4/Dockerfile
    depends_on:
      - db
    ports:
      - 8484:80
    env_file:
      - docker/pgadmin4/pgadmin4.env

  api:
    build:
      context: .
      args:
        PROJECT_NAME: Modalmais.Pix.Api
        EXPOSED_PORT_HTTP: 5002
      dockerfile: docker/api/api.Dockerfile
    depends_on:
      - db
    ports:
      - '5002:5002'